# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

on:
  workflow_call:
    inputs:
      docs_dry_run:
        description: 'Whether we want to push changes to discourse or not'
        required: true
        type: string
    secrets:
      DISCOURSE_API_USERNAME:
        required: true
      DISCOURSE_API_KEY:
        required: true


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run tests
        run: tox run -e unit

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Publish documentation
        uses: deusebio/discourse-gatekeeper@main
        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ inputs.docs_dry_run }}

      - name: Show migrate output
        run: echo '${{ steps.publishDocumentation.outputs.migrate }}'

      - name: Show reconcile output
        run: echo '${{ steps.publishDocumentation.outputs.reconcile }}'

