# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

on:
  pull_request:

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    with:
      docs_dry_run: true
    secrets: inherit
