name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    with:
      docs_dry_run: "false"
    secrets:
      DISCOURSE_API_USERNAME: "${{ secrets.DISCOURSE_API_USERNAME }}"
      DISCOURSE_API_KEY: "${{ secrets.DISCOURSE_API_KEY }}"

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - ci-tests
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
