name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets:
      CHARMHUB_TOKEN: "${{ secrets.CHARMHUB_TOKEN }}"
      AWS_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
      GCP_ACCESS_KEY: "${{ secrets.GCP_ACCESS_KEY }}"
      GCP_SECRET_KEY: "${{ secrets.GCP_SECRET_KEY }}"

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish documentation
        uses: canonical/upload-charm-docs@wip-reconcile-on-tag-condition
        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "false"
      - name: Show index page
        run: echo '${{ steps.publishDocumentation.outputs.index_url }}'

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - ci-tests
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
