name: Detect upstream Spark updates

env:
  BRANCH: main

on:
  schedule:
    - cron: '00 16 * * *'

jobs:

  sync-docs:
    name: Raise PR with community contribution on Discourse
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish documentation
        uses: canonical/upload-charm-docs@wip-reconcile-on-tag-condition

        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"
      - name: Show index page
        run: echo '${{ steps.publishDocumentation.outputs.index_url }}'

